# Generated by Django 3.2.5 on 2021-07-03 14:08

from django.db import migrations, models
import snip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetModel',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=125)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('code', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=snip.models.upload_path)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('python_version', models.CharField(blank=True, max_length=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'snip_snippets',
            },
        ),
    ]
