# Generated by Django 3.2.5 on 2021-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetmodel',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snippetmodel',
            name='python_version',
            field=models.CharField(choices=[('2.7', '2.7'), ('3.0', '3.0'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9')], max_length=5),
        ),
        migrations.AlterField(
            model_name='snippetmodel',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
