# Generated by Django 3.2.5 on 2021-07-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snip', '0004_snippetmodel_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snip.snippetmodel')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snip_upvotes',
            },
        ),
    ]
